### ISSUE TITLE
Add an indicator to show when the video replay is available

### ISSUE THREAD

**Issue by robinlopez** [voxxrin/voxxrin3#106]
**Description:**

Currently, on the cards for past talks, there is no visible indicator to inform users that the video replay is available. It would be helpful to add this indicator to improve the visibility of this information for users.

Additionally, the display of the room (physical location) for past talks no longer seems necessary once the event is over. It is suggested to replace this information with an indicator showing whether the video stream is available or not.

**Tasks:**

- [ ] 	Add a visual indicator on the cards of past talks when the video replay is available.
- [ ] 	Remove the display of the room for finished event.
- [ ] 	Replace the room display with an indicator for video stream a

**Comment by fcamblor** [comment]
Not sure if I'd remove the Room if we don't have the record (even for past talks)

Wondering if this would make sense to mix talks "with record but not rooms" and talks "with rooms because no record" in the same schedule.
I guess it might look weird.

I need to think a little bit about this ... I like the idea to replace room with record indicator, but I'm not sure if both concept are linked each other.

**Comment by robinlopez** [comment]
For me, the idea was to remove the room info only when the **event** is over (not necessarily for past talks). 

Once the event is over, I don't really see any point in displaying this information.

In the case of a conference over several days, and a reactive orga that publishes recorded talks the same evening, perhaps we could also hide the room from the replay information.
